title: Template
author: TeachBooks Team, built with <a href="https://teachbooks.io">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a> #add your own name here
logo: figures/TB_logo.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/TB_favicon.ico"
  baseurl :  "https://teachbooks.io/" #Replace this with your own URL

sphinx:
  config:
    tud_change_logo: True
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_css_files: ["applet.css"] 
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/user/repo" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
  extra_extensions:
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_proof
    - sphinx_togglebutton
    - sphinx_exercise
    - teachbooks_sphinx_grasple
    - sphinx.ext.imgconverter
    - sphinx_tudelft_theme
    - teachbooks_sphinx_tippy
  local_extensions:
    applet: _ext/
    logo: _ext/

bibtex_bibfiles: 
  - references.bib
